// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { defineConfig } from "prisma/config";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `file:${path.join(process.cwd(), "prisma", "dev.db")}`,
  },
  adapter: () => {
    const Database = require("better-sqlite3");
    const db = new Database(path.join(process.cwd(), "prisma", "dev.db"));
    return new PrismaBetterSqlite3(db);
  },
});
